- index.bs
Addresses https://github.com/whatwg/fs/issues/22
`showOpenFilePicker()` is only available in the non-standard portion of the API
***
<a href="https://whatpr.org/fs/29.html" title="Last updated on May 24, 2022, 12:29 AM UTC (efbd58c)">Preview</a> | <a href="https://whatpr.org/fs/29/464b505...efbd58c.html" title="Last updated on May 24, 2022, 12:29 AM UTC (efbd58c)">Diff</a>
> Remove use of showOpenFilePicker in example

- index.bs
Fixes #48.
* …
* …
* …
* Chrome: …
* Firefox: …
* Safari: …
(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)
***
<a href="https://whatpr.org/fs/58.html" title="Last updated on Oct 5, 2022, 11:29 AM UTC (9638b58)">Preview</a> | <a href="https://whatpr.org/fs/58/4785589...9638b58.html" title="Last updated on Oct 5, 2022, 11:29 AM UTC (9638b58)">Diff</a>
> Fix IDL type conversion reference

- index.bs
Updates what looks like an old variable name.
***
<a href="https://whatpr.org/fs/62.html" title="Last updated on Oct 21, 2022, 3:48 PM UTC (ad9cf1f)">Preview</a> | <a href="https://whatpr.org/fs/62/c10ba63...ad9cf1f.html" title="Last updated on Oct 21, 2022, 3:48 PM UTC (ad9cf1f)">Diff</a>
> Change `stream` to `handle`

- index.bs
Editorial change
***
<a href="https://whatpr.org/fs/67.html" title="Last updated on Oct 27, 2022, 5:20 PM UTC (590d66a)">Preview</a> | <a href="https://whatpr.org/fs/67/d64f799...590d66a.html" title="Last updated on Oct 27, 2022, 5:20 PM UTC (590d66a)">Diff</a>
> Fix typo in async iterator

- index.bs
Fixes #64 
Only modernizes getters and setters. There are no constructors in this spec.
***
<a href="https://whatpr.org/fs/68.html" title="Last updated on Oct 28, 2022, 5:10 PM UTC (b722b4f)">Preview</a> | <a href="https://whatpr.org/fs/68/d64f799...b722b4f.html" title="Last updated on Oct 28, 2022, 5:10 PM UTC (b722b4f)">Diff</a>
> Editorial: modernize getters and setters

- index.bs
Fixes #63
Before: {{InvalidStateError Error}}
After: "{{InvalidStateError Error}}" {{DOMException}}
***
<a href="https://whatpr.org/fs/70.html" title="Last updated on Nov 2, 2022, 7:49 AM UTC (4390bf5)">Preview</a> | <a href="https://whatpr.org/fs/70/abad896...4390bf5.html" title="Last updated on Nov 2, 2022, 7:49 AM UTC (4390bf5)">Diff</a>
> Editorial: Change exceptions to be more precise

- index.bs
Fixes #66.
Updates some TODOs to reference a corresponding issue while turning others into HTML comments so they do not render as part of the spec
***
<a href="https://whatpr.org/fs/72.html" title="Last updated on Nov 9, 2022, 5:04 PM UTC (7468203)">Preview</a> | <a href="https://whatpr.org/fs/72/abad896...7468203.html" title="Last updated on Nov 9, 2022, 5:04 PM UTC (7468203)">Diff</a>
> Editorial: Do not render TODO(fivedots) in the spec

- index.bs
This was missed in #8. This will allow https://github.com/WICG/file-system-access/pull/392 to land
***
<a href="https://whatpr.org/fs/75.html" title="Last updated on Nov 17, 2022, 6:52 PM UTC (149aa5a)">Preview</a> | <a href="https://whatpr.org/fs/75/392116b...149aa5a.html" title="Last updated on Nov 17, 2022, 6:52 PM UTC (149aa5a)">Diff</a>
> Editorial: Export "file system entry/parent" term needed by the WICG spec

- index.bs
Fixes #71
I'm happy to bikeshed the exact text for flushing in the comments.
Also updates the `close()` method's description to not mention flushing. I didn't realize this language existed, but it turns out _none_ (!) of the browsers actually flush the file during `close()`, which matches the behavior of most underlying OSes when closing a file descriptor anyways.
Fixing the `close()` algorithm (to address #83) will be done in a follow-up
***
<a href="https://whatpr.org/fs/85.html" title="Last updated on Jan 10, 2023, 9:58 PM UTC (cc64c12)">Preview</a> | <a href="https://whatpr.org/fs/85/048a672...cc64c12.html" title="Last updated on Jan 10, 2023, 9:58 PM UTC (cc64c12)">Diff</a>
> Describe flushing + don't flush on close

- index.bs
Fixes #31
***
<a href="https://whatpr.org/fs/84.html" title="Last updated on Jan 11, 2023, 9:41 PM UTC (5978da3)">Preview</a> | <a href="https://whatpr.org/fs/84/048a672...5978da3.html" title="Last updated on Jan 11, 2023, 9:41 PM UTC (5978da3)">Diff</a>
> Throw TypeError if passed an offset not supported on the underlying OS

- index.bs
Fixes #63
These should have been fixed in #70 but clearly I missed some ¯\\_(ツ)_/¯
***
<a href="https://whatpr.org/fs/88.html" title="Last updated on Jan 12, 2023, 12:56 AM UTC (a91ecef)">Preview</a> | <a href="https://whatpr.org/fs/88/149f02e...a91ecef.html" title="Last updated on Jan 12, 2023, 12:56 AM UTC (a91ecef)">Diff</a>
> Editorial: Change exceptions to be more precise - part 2

- index.bs
Fixes #89
While making this change, I've also confirmed that all uses of "resolve" are properly refed and all exceptions are correctly named.
***
<a href="https://whatpr.org/fs/91.html" title="Last updated on Jan 12, 2023, 6:14 PM UTC (b987256)">Preview</a> | <a href="https://whatpr.org/fs/91/c482c69...b987256.html" title="Last updated on Jan 12, 2023, 6:14 PM UTC (b987256)">Diff</a>
> Editorial: Use xref "throw" and "reject"

- index.bs
Fixes #102
I skimmed the rest of the spec and I _think_ these are the only two instances where class names are not formatted as code.. it's possible I missed other instances, though
***
<a href="https://whatpr.org/fs/104.html" title="Last updated on Mar 16, 2023, 9:02 AM UTC (06e554c)">Preview</a> | <a href="https://whatpr.org/fs/104/2d0b5c8...06e554c.html" title="Last updated on Mar 16, 2023, 9:02 AM UTC (06e554c)">Diff</a>
> Editorial: Use <code> formatting for class names in some algorithms

- review-drafts/2023-03.bs
The [March 2023 Review Draft](https://fs.spec.whatwg.org/review-drafts/2023-03/) for this Workstream will be published shortly after merging this pull request.
Under the [WHATWG IPR Policy](https://whatwg.org/ipr-policy), Participants may, within 45 days after publication of a Review Draft, exclude certain Essential Patent Claims from the Review Draft Licensing Obligations. See the [IPR Policy](https://whatwg.org/ipr-policy) for details.
***
<a href="https://whatpr.org/fs/105.html" title="Last updated on Mar 20, 2023, 8:08 AM UTC (f1ec2d2)">Preview</a> | <a href="https://whatpr.org/fs/105/bb07d59...f1ec2d2.html" title="Last updated on Mar 20, 2023, 8:08 AM UTC (f1ec2d2)">Diff</a>
> Review Draft Publication: March 2023

- index.bs
Fixes #59
A much more thorough (than #30) attempt at expressing that FileSystemHandles map to file paths. At a high level, it proposes that:
- A FileSystemHandle has an associated "file system locator"
- A "file system locator" contains, among other things, a "file system path"
- A "file system entry" can be located given a "file system locator"
- You can get a "file system locator" from a "file system entry"
See #59 for the implications of this in practice.
* Chromium
* WebKit
* Specifying that FileSystemHandles are path-based will allow us to clarify many tests which are currently intentionally vague  as to hide the ambiguity whether handles are paths or references
* Chromium: https://crbug.com/1426855
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1823961
* WebKit: …
> Give FileSystemHandles an associated path

- index.bs
This fixes bikeshed [link error](https://speced.github.io/bikeshed/#ambi-for).
***
<a href="https://whatpr.org/fs/117.html" title="Last updated on May 8, 2023, 11:11 PM UTC (98113d1)">Preview</a> | <a href="https://whatpr.org/fs/117/8360b75...98113d1.html" title="Last updated on May 8, 2023, 11:11 PM UTC (98113d1)">Diff</a>
> Editorial: Fix ambiguous link for directory entry children

- proposals/MultipleReadersWriters.md
This PR adds a proposal to support multiple readers and writers in FileSystemSyncAccessHandle (https://github.com/whatwg/fs/issues/34) and FileSystemWritableFileStream, describing new locking schemes.
> Add proposal for Multiple Readers and Writers

- proposals/FileSystemObserver.md
Proposal for a new interface which allows a website to be notified of changes to files and directories.
See #123 and https://github.com/WICG/file-system-access/issues/72
> Add proposal for the FileSystemObserver interface

- index.bs
Fixes #74 by specifying a parallel queue for all file system operations, not just locking (see https://github.com/whatwg/fs/pull/9/files#r1109679577)
* Chromium
* WebKit
* N/A (unless there's a way to deterministically test race conditions that I don't know about)
* Chromium: ...
* Gecko: …
* WebKit: …
***
<a href="https://whatpr.org/fs/95.html" title="Last updated on Jun 13, 2023, 4:32 PM UTC (ba5a295)">Preview</a> | <a href="https://whatpr.org/fs/95/8360b75...ba5a295.html" title="Last updated on Jun 13, 2023, 4:32 PM UTC (ba5a295)">Diff</a>
> Define a parallel queue for all file system operations

- index.bs
Fixes #103
Related to #92 and #109
Gives a FileSystemHandle an "is in an origin private file system" predicate which checks for the empty string in its path
***
<a href="https://whatpr.org/fs/110.html" title="Last updated on Apr 6, 2023, 11:27 PM UTC (9d65def)">Preview</a> | <a href="https://whatpr.org/fs/110/274a106...9d65def.html" title="Last updated on Apr 6, 2023, 11:27 PM UTC (9d65def)">Diff</a>
> Specify "origin private file system"-ness on a FileSystemHandle

- index.bs
Fixes #92
***
<a href="https://whatpr.org/fs/129.html" title="Last updated on Jun 16, 2023, 9:40 PM UTC (4fadcaf)">Preview</a> | <a href="https://whatpr.org/fs/129/d636c34...4fadcaf.html" title="Last updated on Jun 16, 2023, 9:40 PM UTC (4fadcaf)">Diff</a>
> Rename the Origin Private File System to the Bucket File System

- proposals/FileSystemObserver.md
Also clarifies one sentence about resource consumption on Linux. File descriptors and watch descriptors are each consumed (though generally more of the latter)
> Meta: Fix broken link in FileSystemObserver proposal

- index.bs
Before: `{{WriteCommandType/"write"}}`
After: `"{{WriteCommandType/write}}"`
Fixes #133
***
<a href="https://whatpr.org/fs/134.html" title="Last updated on Jun 20, 2023, 9:42 PM UTC (cee9c6e)">Preview</a> | <a href="https://whatpr.org/fs/134/69c51d3...cee9c6e.html" title="Last updated on Jun 20, 2023, 9:42 PM UTC (cee9c6e)">Diff</a>
> Editorial: Properly format enum strings

- index.bs
Using backticks is not supported within [=links=] 
Upstream PR to export the error names table is here: https://github.com/whatwg/webidl/pull/1325
***
<a href="https://whatpr.org/fs/135.html" title="Last updated on Jun 21, 2023, 7:17 AM UTC (fac2c1f)">Preview</a> | <a href="https://whatpr.org/fs/135/69c51d3...fac2c1f.html" title="Last updated on Jun 21, 2023, 7:17 AM UTC (fac2c1f)">Diff</a>
> Editorial: Fix broken link to DOMException names table

- proposals/FileSystemObserver.md
An example in the FileSystemObserver explainer has a callback that uses the await operator but is not an async function. This makes it an async function.
> Meta: Fix an example in the FileSystemObserver explainer

- proposals/MultipleReadersWriters.md
Updates explainer introduction so that "readwrite-unsafe" is included in the example.
> Meta: Update Explainer Introduction to include "readwrite-unsafe" example.

- proposals/MultipleReadersWriters.md
Adds a section to the proposal to explain interaction with the BFCache.
***
<a href="https://whatpr.org/fs/142.html" title="Last updated on Dec 9, 2023, 1:02 AM UTC (5397fe3)">Preview</a> | <a href="https://whatpr.org/fs/142/bd6ef5a...5397fe3.html" title="Last updated on Dec 9, 2023, 1:02 AM UTC (5397fe3)">Diff</a>
> Add BFCache section to multi reader writer proposal

- proposals/FileSystemObserver.md
- Updates `FileSystemChangeType` names from created/deleted/unsupported to appeared/disappeared/unknown:
- When a file or directory has been moved into (or out of) the watched scope, the file/dir is to be reported as "created" or "deleted" with respect to the scope; however, this naming may be confusing as it is not really newly created file/dir (or deleted). Therefore, new names "appeared" and "disappeared" are suggested instead.
- "unsupported" is renamed to "unknown" to indicate a general use case where a type is not known or not to be specified to the site for various reasons.
- Change the data type of `FileSystemChangeRecord.relativePathMovedFrom`
- Providing a `FileSystemHandle` to a non-existing file would not make much sense, but it would be still useful for sites to know where a …
> Update FileSystemObserver explainer

- index.bs
QuotaExceededError is graduating from being a DOMException name into a new error class, in https://github.com/whatwg/webidl/pull/1465. Update creation sites to reflect this.
For now, the quota and requested properties are left at their default (null). Future work could include setting them in an informative fashion.
* See https://github.com/whatwg/webidl/pull/1465
* Yes, https://github.com/web-platform-tests/wpt/pull/53645 includes some updates here
* See https://github.com/whatwg/webidl/pull/1465
(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)
***
<a href="https://whatpr.org/fs/171.html" title="Last updated on Sep 13, 2025, 12:41 AM UTC (c90e51b)">Preview</a> | <a href="https://whatpr.org/fs/171/28a8342...c90e51b.html" title="Last updated …
> Update QuotaExceededError usage
